# Root redirectory
index.php /usr/share/php/passbolt-api/

# All from app/ besides Vendor/ and Config
## This goes to /etc/passbolt
# app/Config /usr/share/php/passbolt-api/app/
app/Console /usr/share/php/passbolt-api/app/
app/Controller /usr/share/php/passbolt-api/app/
app/.htaccess /usr/share/php/passbolt-api/app/
app/index.php /usr/share/php/passbolt-api/app/
app/Lib /usr/share/php/passbolt-api/app/
app/Locale /usr/share/php/passbolt-api/app/
app/Model /usr/share/php/passbolt-api/app/
app/Plugin /usr/share/php/passbolt-api/app/
app/Test /usr/share/php/passbolt-api/app/
## This goes to /var/lib/passbolt
# app/tmp /usr/share/php/passbolt-api/app/
## This goes to php-passbolt-embedded
# app/Vendor /usr/share/php/passbolt-api/app/
app/View /usr/share/php/passbolt-api/app/
app/webroot /usr/share/php/passbolt-api/app/

# Configuration files
app/Config/acl.ini.php /etc/passbolt/
app/Config/acl.php /etc/passbolt/
app/Config/bootstrap.php /etc/passbolt/
app/Config/default.php /etc/passbolt/
app/Config/routes.php /etc/passbolt/
app/Config/version.php /etc/passbolt/
