# Root redirectory
index.php /usr/share/php/passbolt-api/
.htaccess /usr/share/php/passbolt-api/

# Source
src /usr/share/php/passbolt-api/
bin /usr/share/php/passbolt-api/
index.php /usr/share/php/passbolt-api/
plugins /usr/share/php/passbolt-api/
src /usr/share/php/passbolt-api/
webroot /usr/share/php/passbolt-api/

# Configuration files
config/* /etc/passbolt/

# All temporary files
tmp/* /var/lib/passbolt/tmp/
